[workspace]
members = [
    "crates/CoGrRs",
    "crates/gpu",
    "crates/ui"
]
resolver = "2"


[workspace.package]
edition = "2021"
rust-version = "1.65"
keywords = ["graphics"]
repository = "https://github.com/jasperdewinther/CoGrRs"
version = "0.1.0"

[profile.release]
debug = true